### ISSUE TITLE
User-defined classes should not inherit from BaseException

### ISSUE THREAD

**Issue by timjstewart** [kata198/func_timeout#11]
https://github.com/kata198/func_timeout/blob/50baa8db502fd24acc0f2a1bc473649505336997/func_timeout/exceptions.py#L12

See: https://docs.python.org/3/library/exceptions.html#BaseException

**Comment by Laurens-T** [comment]
Not sure if anything is going to change since there hasn't been a response on this issue in over a year, but I bumped into this as well. I was testing something with this library and noticed that the following snippet didn't work exactly as expected. It would be nice if the `FunctionTimedOut` class could just inherit from `Exception` just as timjstewart mentioned.

```python
from func_timeout import func_set_timeout

@func_set_timeout(1.0)
def method():
    import time
    time.sleep(1.5)

try:
    method()
except Exception as e:
    print('Expect to catch the FunctionTimedOut here')
except BaseException as e:
    print('But it is actually caught here')
```

**Comment by kata198** [comment]
This is fundamental to the design and cannot be changed. Your blanket exceptions are the issue, not the library. If you need blanket exceptions, catch FunctionTimedOut specifically in your first handler, and raise

except FunctionTimedOut:
   raise
except BaseException:
    ....

See documentation that mentions this specifically.
