### ISSUE TITLE
func_timeout is not working

### ISSUE THREAD

**Issue by arunmastermind** [kata198/func_timeout#13]
Hi, 

I am using a very simple code:

```
from func_timeout import func_timeout, FunctionTimedOut, func_set_timeout
import time

def test_time(a):
        print(f'start')
        time.sleep(8)
        print(f'end !!!')
        return a

try:
    y = func_timeout(5, test_time(),  args=(123))
    print(f'y is {y}')
except FunctionTimedOut:
    print("timeout")
except Exception as e:
    print(e)
```

I am trying to get a timeout error/exception but rater seems that the args are not getting passed to the function itself and getting an error as:

> ERROR: test_time() missing 1 required positional argument: 'a'

if I hardcode the parameter too as:
```
from func_timeout import func_timeout, FunctionTimedOut, func_set_timeout
import time

def test_time(**a=123**):
        print(f'start')
        time.sleep(2)
        print(f'end !!!')
        return a

try:
    y = func_timeout(5, test_time(),  args=(123))
    print(f'y is {y}')
except FunctionTimedOut:
    print("timeout")
except Exception as e:
    print(e)
```

then I get an error as:

> ERROR: int object argument after * must be an iterable, not int

could you pease suggest something for this so that I can get a timeout exception for a function call taking more than the desired time

**Comment by florczakraf** [comment]
There are two problems with your code, both in the following line:

```
    y = func_timeout(5, test_time(),  args=(123))
```

First of all, you're supposed to pass a function as 2nd argument. What you did instead, was to call it prematurely (with a wrong signature, that's why you got `test_time() missing 1 required positional argument: 'a'`). Secondly, `args` are supposed to be a tuple (perhaps some other iterables will work as well).

The problematic line after needed changes:
```
    y = func_timeout(5, test_time,  args=(123,))
```

**Comment by PriyankaSagwekar** [comment]
Thanks. This was helpful.
